language: erlang
env:
  - LUA=""
  - LUA="luajit"
install:
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install busted
  - sudo luarocks make
script: "make test"
notifications:
  email:
    - ellengummesson+travis-ci@gmail.com
